name: CI-Testing

on:
  push:
    branches:
      - prod

jobs:
  app-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3  
    
    steps:
    - uses: actions/checkout@v1

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: run the app
      run: |
        php artisan serve &
        
    - name: Health check
      run: |
        curl http://localhost:8000/health-check | grep good
